import type { Metadata } from "next";
import "./globals.css";
import FeatureSidebar from "@/components/layout/feature-sidebar";
import TopBar from "@/components/layout/top-bar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ChatLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <FeatureSidebar />
      <TopBar />
      {children}
    </>
  );
}
